### PR TITLE
[2.x] Add sanctum:prune-expired command for removing expired tokens.

### PR DESCRIPTION
**Pull request by yuraplohov**
This command has long been needed by developers.
A similar command is present in Telescope and Passport packages.

### CODE REVIEW

**Comment by ankurk91** [comment]
The command does not return any thing.
The exit codes must be added

**Comment by driesvints** [comment]
Thanks @ankurk91. I sent in a PR for that: https://github.com/laravel/sanctum/pull/351

**Comment by EdgarSedov** [comment]
@yuraplohov @ankurk91 @driesvints 
Hey guys, thanks for awesome command, it's good that we don't need to write it ourselves.

I have one question - is there any special reason why we use `created_at` instead of `last_used_at`?

**Comment by yuraplohov** [comment]
Thank you, @EdgarSedov 

I used `created_at` in this logic, because expiration of token in Sanctum based on `created_at` exactly. Maybe, expiration by `last_used_at` is needed in this package, but that's another question. I saw PR [#349](https://github.com/laravel/sanctum/pull/349) with this idea recently.

**Pull request merged**
