### PR TITLE
Add regenerateToken method to HasApiTokens

### PR DESCRIPTION
**Pull request by FatefulNur**
This PR introduces new `regenerateToken` method to the `HasApiTokens` traits in **Laravel Sanctum**. This method allows users to regenerate a new personal access token while revoking the existing one.

### Changes:

- Added `regenerateToken` method to the `HasApiTokens` traits and contract.
- Implemented functionality to delete existing tokens and generate a new one with specified attributes.

### Use-Case

For scenarios requiring frequent rotation of access tokens to mitigate security risks, the addition of a `regenerateToken` method to Laravel Sanctum can greatly simplify token management without manually creating it into our own model.

### Testing:

A unit test have been added to ensure the proper functionality of the `regenerateToken` method.

### CODE REVIEW

**Comment by RahulDey12** [comment]
why it's deleting all the token it should delete the transit token instead of all.

**Comment by FatefulNur** [comment]
@RahulDey12 thanks for your advice. Could you tell what's the regard to delete only the transient token?

**Comment by RahulDey12** [comment]
It mean that we are logging out.

**Comment by FatefulNur** [comment]
@RahulDey12 yes said absolute. But `TransientToken` Isn't store into the database. So deleting it might meaning less. Should I close this PR then? Or You have any other opinion about this?

**Comment by FatefulNur** [comment]
May be the idea wasn't relevant with api tokens.

**Pull request closed without merging**
